name: flextravel
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_messaging: ^15.0.0
  cloud_firestore: ^5.0.0
  flutter_easyloading: ^3.0.5
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
  - family: NunitoSans
    fonts:
      - asset: assets/fonts/NunitoSans_Regular.ttf
      - asset: assets/fonts/NunitoSans_Light.ttf
        weight: 300
      - asset: assets/fonts/NunitoSans_SemiBold.ttf
        weight: 600
      - asset: assets/fonts/NunitoSans_Bold.ttf
        weight: 700
      - asset: assets/fonts/NunitoSans_ExtraBold.ttf
        weight: 800

  - family: Gelasio
    fonts:
      - asset: assets/fonts/Gelasio_Regular.ttf
      - asset: assets/fonts/Gelasio_Medium.ttf
        weight: 500
      - asset: assets/fonts/Gelasio_SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Gelasio_Bold.ttf
        weight: 700

  - family: Merriweather
    fonts:
      - asset: assets/fonts/Merriweather_Regular.ttf
      - asset: assets/fonts/Merriweather_Bold.ttf
        weight: 700
  